Index page
Misori-simon/building-with-responsive-design pull request #1
Opened 2020-10-07 15:14 UTC by Misori-simon

# THE NEXT WEB homepage

## Intro

We have used several techniques like flexbox, position, float, and grid to layout our website and make it responsive. And it's about The New Web's Home Page.

## About the Project

This project is about building a responsive website using the various positioning and display values from the mobile view up to the desktop. The website has two breakpoints 676px and 1023px

2020-10-07 16:03 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great job working on the project!!
:100: Great that you use GitHub pages
:100: Awesome that you have a licence
:100: Descriptive README
:100: Descriptive PR

## Required Changes
### [Mandatory] :red_circle: 

- [x] Footer should be outside the ```<main>```

- [x] Maintain alignment and indentation consistent through all the file. See inline comments

- [x] Latest Deals elements differ from original
![image](https://user-images.githubusercontent.com/25774518/95355905-b2501080-088b-11eb-981b-45910254af11.png)

- [x] Sections don't take the full width on larger screens 1440
![image](https://user-images.githubusercontent.com/25774518/95356000-ceec4880-088b-11eb-92a9-264705b42d52.png)

- [x] Not all elements on navbar look like the original on table mode
![image](https://user-images.githubusercontent.com/25774518/95356146-fb07c980-088b-11eb-8ffc-0ee051db1589.png)

- [x] latest funding only show 3 elements on tablet mode
![image](https://user-images.githubusercontent.com/25774518/95356270-18d52e80-088c-11eb-93c8-23f19fa28e4c.png)

- [x] Image distorting and overlaping text on tablet mode
![image](https://user-images.githubusercontent.com/25774518/95356337-2b4f6800-088c-11eb-8378-0cff711b98d5.png)

- [x] Navbar doesn't look like original on mobile view
![image](https://user-images.githubusercontent.com/25774518/95356447-4ae69080-088c-11eb-8f14-2f73a1e12df5.png)

- [x] Latest funding show only 3 elements on mobile view
![image](https://user-images.githubusercontent.com/25774518/95356546-66519b80-088c-11eb-9347-2ab92be4067a.png)

- [x] Image overlaping text on mobile view
![image](https://user-images.githubusercontent.com/25774518/95356601-779aa800-088c-11eb-9683-e1f8d614654c.png)

- [x] Footer doesn't look as original on mobile view
![image](https://user-images.githubusercontent.com/25774518/95356702-900ac280-088c-11eb-84f8-3ed428dfe5ff.png)

### [OPTIONAL]  :large_blue_circle: 

- [ ] Maintain the CSS file DRY.

- [ ] For future project choose a meaningful name for the feature branch. Example:
**Actual**: ```index-page```
**Improved** :+1:  : ```thenextweb-clone```

### [Comments] :green_circle: 

- A great tool to test if the project looks as intended in different screen sizes is the browser media query inspector.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-07 16:08 UTC, jubaan requested changes

2020-10-07 16:08 UTC, jubaan commented on index.html
> +</html>
Fix indentation and alignment as required

2020-10-08 11:18 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**
- [x] Please use different images and text for each image. This will help you to show your project effectively. 

- [x] on the top nav-bar you didn't use actual search icon. 

- [x] Latest funding section should look like this.
![chrome-capture (27)](https://user-images.githubusercontent.com/58504655/95451699-9b8be580-0981-11eb-99b4-1e4a3142e874.jpg)

- [x] Top nav-bar should be sticky in all screens. 

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-08 14:26 UTC, jubaan requested changes
# Status: Changes Required :recycle:

Great job working on the previous required changes, there are still some issues that need to be addressed. 

## Required Changes
### [Mandatory] :red_circle: 

- [ ] Latest funding doesn't match original in tablet view
![image](https://user-images.githubusercontent.com/25774518/95471485-9a3dc700-0947-11eb-94ce-8e045eefa969.png)

- [ ] Latest funding only shows 3 elements in mobile view
![image](https://user-images.githubusercontent.com/25774518/95471644-c6f1de80-0947-11eb-8217-5abbb492c24e.png)

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-08 14:47 UTC, arslanbisharat approved these changes
Congratslutons Approved 🎉
Hello Developer 👋
You are on 🔥
Thank you so much for making those changes and I am very happy to approve the project. You have done a great job. 👏
Please keep working hard and move forward with your curriculum.
Looking forward to seeing your next project. 😄
---------------------------------------------------------------------------------------------------------------
**To highlight**
- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

- [ ] Please use descriptive commit messages. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-10-08 14:48 UTC, merged